/*
 * GENERATED FILE -- DO NOT EDIT.
 *
 * Produced by tools/generate_commands.py from docs/jlink-api-asynchronous.md.
 * Edit the generator, not this file; every run overwrites the whole rawcommands tree.
 */

package com.asyncjlink.commands.rawcommands.solid;

import com.asyncjlink.commands.Command;
import com.asyncjlink.commands.CommandException;
import com.asyncjlink.commands.CreoContext;
import com.asyncjlink.commands.Marshal;
import com.asyncjlink.json.JsonObject;
import com.asyncjlink.json.JsonSchema;

import com.ptc.cipjava.jxthrowable;
import com.ptc.pfc.pfcFeature.FeatureType;
import com.ptc.pfc.pfcSolid.Solid;

/**
 * Solid.ListFeaturesByType &mdash; pfcSolid.
 *
 * <pre>
 * Features ListFeaturesByType(Boolean, FeatureType) throws jxthrowable
 * </pre>
 */
public final class SolidListFeaturesByTypeCommand implements Command {

    @Override public String name() { return "Solid.ListFeaturesByType"; }
    @Override public String jlinkPackage() { return "pfcSolid"; }
    @Override public String receiverType() { return "Solid"; }
    @Override public String signature() { return "Features ListFeaturesByType(Boolean, FeatureType) throws jxthrowable"; }

    @Override
    public JsonSchema paramSchema() {
        return JsonSchema.object()
                .describedAs("Solid.ListFeaturesByType \u2014 pfcSolid")
                .required("target", JsonSchema.handle("Solid"),
                        "The Solid to act on.")
                .optional("flag", JsonSchema.bool(),
                        "Boolean value.")
                .optional("featureType", JsonSchema.enumOf("FeatureType", "FEATTYPE_FIRST", "FEATTYPE_HOLE", "FEATTYPE_SHAFT", "FEATTYPE_ROUND", "FEATTYPE_CHAMFER", "FEATTYPE_SLOT", "FEATTYPE_CUT", "FEATTYPE_PROTRUSION", "FEATTYPE_NECK", "FEATTYPE_FLANGE", "FEATTYPE_RIB", "FEATTYPE_EAR", "FEATTYPE_DOME", "FEATTYPE_DATUM_PLANE", "FEATTYPE_LOC_PUSH", "FEATTYPE_UDF", "FEATTYPE_DATUM_AXIS", "FEATTYPE_DRAFT", "FEATTYPE_SHELL", "FEATTYPE_DOME2", "FEATTYPE_CORNER_CHAMFER", "FEATTYPE_DATUM_POINT", "FEATTYPE_IMPORT", "FEATTYPE_COSMETIC", "FEATTYPE_ETCH", "FEATTYPE_MERGE", "FEATTYPE_MOLD", "FEATTYPE_SAW", "FEATTYPE_TURN", "FEATTYPE_MILL", "FEATTYPE_DRILL", "FEATTYPE_OFFSET", "FEATTYPE_DATUM_SURFACE", "FEATTYPE_REPLACE_SURFACE", "FEATTYPE_GROOVE", "FEATTYPE_PIPE", "FEATTYPE_DATUM_QUILT", "FEATTYPE_ASSEMBLY_CUT", "FEATTYPE_UDFTHREAD", "FEATTYPE_CURVE", "FEATTYPE_SURFACE_MODEL", "FEATTYPE_WALL", "FEATTYPE_BEND", "FEATTYPE_UNBEND", "FEATTYPE_SHEETMETAL_CUT", "FEATTYPE_FORM", "FEATTYPE_THICKEN", "FEATTYPE_BEND_BACK", "FEATTYPE_UDFNOTCH", "FEATTYPE_UDFPUNCH", "FEATTYPE_INTERNAL_UDF", "FEATTYPE_SPLIT_SURFACE", "FEATTYPE_GRAPH", "FEATTYPE_SMMFGPUNCH", "FEATTYPE_SMMFGCUT", "FEATTYPE_FLATTEN", "FEATTYPE_SET", "FEATTYPE_VDA", "FEATTYPE_SMMFGFORM", "FEATTYPE_SHEETMETAL_PUNCH_POINT", "FEATTYPE_LIP", "FEATTYPE_MANUAL_MILL", "FEATTYPE_MFGGATHER", "FEATTYPE_MFGTRIM", "FEATTYPE_MFGUSE_VOLUME", "FEATTYPE_CABLE_LOCATION", "FEATTYPE_CABLE_SEGMENT", "FEATTYPE_CABLE", "FEATTYPE_COORD_SYS", "FEATTYPE_CHANNEL", "FEATTYPE_AREA_NIBBLE", "FEATTYPE_PATCH", "FEATTYPE_PLY", "FEATTYPE_CORE", "FEATTYPE_EXTRACT", "FEATTYPE_MFGREFINE", "FEATTYPE_SILHOUETTE_TRIM", "FEATTYPE_SPLIT", "FEATTYPE_EXTEND", "FEATTYPE_SOLIDIFY", "FEATTYPE_INTERSECT", "FEATTYPE_ATTACH", "FEATTYPE_CROSS_SECTION", "FEATTYPE_UDFZONE", "FEATTYPE_UDFCLAMP", "FEATTYPE_DRILL_GROUP", "FEATTYPE_ISEGMENT", "FEATTYPE_CABLE_COSMETIC", "FEATTYPE_SPOOL", "FEATTYPE_COMPONENT", "FEATTYPE_MFGMERGE", "FEATTYPE_FIXTURE_SETUP", "FEATTYPE_FLAT_PAT", "FEATTYPE_CONT_MAP", "FEATTYPE_EXP_RATIO", "FEATTYPE_RIP", "FEATTYPE_OPERATION", "FEATTYPE_WORKCELL", "FEATTYPE_CUT_MOTION", "FEATTYPE_CUSTOMIZE", "FEATTYPE_DRV_TOOL_SKETCH", "FEATTYPE_DRV_TOOL_EDGE", "FEATTYPE_DRV_TOOL_CURVE", "FEATTYPE_DRV_TOOL_SURF", "FEATTYPE_MATERIAL_REMOVAL", "FEATTYPE_TORUS", "FEATTYPE_PIPE_SET_START", "FEATTYPE_PIPE_POINT_TO_POINT", "FEATTYPE_PIPE_EXTEND", "FEATTYPE_PIPE_TRIM", "FEATTYPE_PIPE_FOLLOW", "FEATTYPE_PIPE_JOIN", "FEATTYPE_AUXILIARY", "FEATTYPE_PIPE_LINE", "FEATTYPE_LINE_STOCK", "FEATTYPE_SOLID_PIPE", "FEATTYPE_BULK_OBJECT", "FEATTYPE_SHRINKAGE", "FEATTYPE_PIPE_JOINT", "FEATTYPE_PIPE_BRANCH", "FEATTYPE_DRV_TOOL_TWO_CNTR", "FEATTYPE_SUB_HARNESS", "FEATTYPE_SHEETMETAL_OPTIMIZE", "FEATTYPE_DECLARE", "FEATTYPE_SHEETMETAL_POPULATE", "FEATTYPE_OPERATION_COMPONENT", "FEATTYPE_MEASURE", "FEATTYPE_DRAFT_LINE", "FEATTYPE_REMOVE_SURFACES", "FEATTYPE_RIBBON_CABLE", "FEATTYPE_ATTACH_VOLUME", "FEATTYPE_BLD_OPERATION", "FEATTYPE_UDFWORK_REGION", "FEATTYPE_SPINAL_BEND", "FEATTYPE_TWIST", "FEATTYPE_FREE_FORM", "FEATTYPE_ZONE", "FEATTYPE_WELDING_ROD", "FEATTYPE_WELD_FILLET", "FEATTYPE_WELD_GROOVE", "FEATTYPE_WELD_PLUG_SLOT", "FEATTYPE_WELD_SPOT", "FEATTYPE_SHEETMETAL_SHEAR", "FEATTYPE_RIBBON_PATH", "FEATTYPE_RIBBON_EXTEND", "FEATTYPE_ASSEMBLY_CUT_COPY", "FEATTYPE_DEFORM_AREA", "FEATTYPE_RIBBON_SOLID", "FEATTYPE_FLAT_RIBBON_SEGMENT", "FEATTYPE_POSITION_FOLD", "FEATTYPE_SPRING_BACK", "FEATTYPE_BEAM_SECTION", "FEATTYPE_SHRINK_DIM", "FEATTYPE_THREAD", "FEATTYPE_SHEETMETAL_CONVERSION", "FEATTYPE_CMMMEASURE_STEP", "FEATTYPE_CMMCONSTR", "FEATTYPE_CMMVERIFY", "FEATTYPE_CAV_SCAN_SET", "FEATTYPE_CAV_FIT", "FEATTYPE_CAV_DEVIATION", "FEATTYPE_SHEETMETAL_ZONE", "FEATTYPE_SHEETMETAL_CLAMP", "FEATTYPE_PROCESS_STEP", "FEATTYPE_EDGE_BEND", "FEATTYPE_DRV_TOOL_PROFILE", "FEATTYPE_EXPLODE_LINE", "FEATTYPE_GEOM_COPY", "FEATTYPE_ANALYSIS", "FEATTYPE_WATER_LINE", "FEATTYPE_UDFRMDT", "FEATTYPE_VOL_SPLIT", "FEATTYPE_WELD_EDGE_PREP", "FEATTYPE_SMMFGOFFSET", "FEATTYPE_SMMFGMATERIAL_REMOVE", "FEATTYPE_SMMFGCOSMETIC", "FEATTYPE_SMMFGAPPROACH", "FEATTYPE_SMMFGSLOT", "FEATTYPE_SMMFGSHAPE", "FEATTYPE_IPMQUILT", "FEATTYPE_USER", "FEATTYPE_GROUP_HEAD", "FEATTYPE_DRVD", "FEATTYPE_SMT_CRN_REL", "FEATTYPE_SLDBEND", "FEATTYPE_FLATQLT", "FEATTYPE_DRV_TOOL_TURN", "FEATTYPE_HULL_PLATE", "FEATTYPE_HULL_HOLE", "FEATTYPE_HULL_CUTOUT", "FEATTYPE_HULL_STIFFENER", "FEATTYPE_HULL_BEAM", "FEATTYPE_HULL_ENDCUT", "FEATTYPE_HULL_WLD_FLANGE", "FEATTYPE_HULL_COLLAR", "FEATTYPE_HULL_DRAW", "FEATTYPE_HULL_BRACKET", "FEATTYPE_HULL_FOLDED_FLG", "FEATTYPE_FR_SYS", "FEATTYPE_HULL_COMPT", "FEATTYPE_REFERENCE", "FEATTYPE_SHELL_EXP", "FEATTYPE_FREEFORM", "FEATTYPE_KERNEL", "FEATTYPE_WELD_PROCESS", "FEATTYPE_HULL_REP_TMP", "FEATTYPE_INSULATION", "FEATTYPE_SLD_PIP_INSUL", "FEATTYPE_SMT_EXTRACT", "FEATTYPE_ASSY_MERGE", "FEATTYPE_DS_OPTIMIZE", "FEATTYPE_COMP_INTERFACE", "FEATTYPE_OLE", "FEATTYPE_TERMINATOR", "FEATTYPE_WELD_NOTCH", "FEATTYPE_ASSY_WELD_NOTCH", "FEATTYPE_ROUTE_MANAGER", "FEATTYPE_HULL_WELD_NOTCH", "FEATTYPE_SMM_SLIT", "FEATTYPE_SMM_HOLE", "FEATTYPE_SMM_NEST", "FEATTYPE_SMM_GROOVE", "FEATTYPE_SMM_ETCH", "FEATTYPE_ROUTE_PATH", "FEATTYPE_HULL_SPLIT_BOUND", "FEATTYPE_SUPERQUILT", "FEATTYPE_MOLD_SLIDER", "FEATTYPE_HULL_PAD", "FEATTYPE_ROUTE_SPOOL", "FEATTYPE_GLOBAL_MODEL", "FEATTYPE_HULL_MITRE", "FEATTYPE_HULL_SLOTCUT", "FEATTYPE_PATTERN", "FEATTYPE_PATTERN_HEAD", "FEATTYPE_FLEX_MUTATOR", "FEATTYPE_ANNOTATION", "FEATTYPE_GRANITE_REMOVE_SRFS", "FEATTYPE_GRANITE_TAPER_EXTR", "FEATTYPE_GRANITE_TOOL_COMP", "FEATTYPE_STYLE", "FEATTYPE_GENERAL_MERGE", "FEATTYPE_DAMPER", "FEATTYPE_SPRING", "FEATTYPE_AUTO_ROUND", "FEATTYPE_DESIGNATED_AREA", "FEATTYPE_REMOVE_SURFACE", "FEATTYPE_ARTWORK", "FEATTYPE_WELD_COMBINE", "FEATTYPE_CONTACT3D", "FEATTYPE_RS_GENERATOR", "FEATTYPE_RS_TRJ_MOVE", "FEATTYPE_PLASTIC_RIB", "FEATTYPE_PM_BELT_CURVE", "FEATTYPE_VPDD", "FEATTYPE_SUBDIVISION", "FEATTYPE_FLEXMOVE", "FEATTYPE_PM_BUSHING_LD", "FEATTYPE_FLXATTACH", "FEATTYPE_FLEXSUBST", "FEATTYPE_MOD_ROUND", "FEATTYPE_CE_GEOM", "FEATTYPE_ANALYT_GEOM", "FEATTYPE_STAMPED_AREA", "FEATTYPE_FLX_OGF", "FEATTYPE_CE_COMP", "FEATTYPE_MFGPTM_MATREM", "FEATTYPE_SPLIT_SRF_RGN", "FEATTYPE_DERIVED_MEMBER", "FEATTYPE_ACCEPT_CRITERIA", "FEATTYPE_MOLD_SHUTOFF_SRF", "FEATTYPE_SMT_SKETCH_FORM", "FEATTYPE_JOIN_WALLS", "FEATTYPE_FLX_SOLVER", "FEATTYPE_CE_SKET", "FEATTYPE_MOLD_SKIRT_EXT_FEAT", "FEATTYPE_MOLD_SKIRT_FILL_FEAT", "FEATTYPE_MOD_CHAMFER", "FEATTYPE_RCG_ROUND", "FEATTYPE_RCG_CHAMFER", "FEATTYPE_UNRCG_ROUND", "FEAT_UNRCG_CHAMFER"),
                        "One of the FeatureType constants.")
                ;
    }

    @Override
    public JsonObject execute(CreoContext ctx, JsonObject params) throws jxthrowable {
        Solid target = Marshal.in(ctx, params.get("target"),
                "Solid", Solid.class, "target");
        if (target == null) {
            throw new CommandException("Field 'target' is required", "invalid_params");
        }
        Boolean flag = Marshal.in(ctx, params.get("flag"),
                "Boolean", Boolean.class, "flag");
        FeatureType featureType = Marshal.in(ctx, params.get("featureType"),
                "FeatureType", FeatureType.class, "featureType");
        return Marshal.result(ctx, target.ListFeaturesByType(flag, featureType), "Features");
    }
}
